export enum ErrorCode {
  PARKING_LOT_NOT_FOUND = 'PARKING_LOT_NOT_FOUND',
  PARKING_FLOOR_NOT_FOUND = 'PARKING_FLOOR_NOT_FOUND',
  PARKING_SPOT_NOT_FOUND = 'PARKING_SPOT_NOT_FOUND',
  PARKING_LOT_CONFLICT = 'PARKING_LOT_CONFLICT',
  PARKING_FLOOR_CONFLICT = 'PARKING_FLOOR_CONFLICT',
  PARKING_SPOT_CONFLICT = 'PARKING_SPOT_CONFLICT',
  INVALID_SPOT_STATUS_TRANSITION = 'INVALID_SPOT_STATUS_TRANSITION',
}
